# Generated by Django 5.2.6 on 2025-09-18 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo')),
                ('f_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('f_actualizacion', models.DateField(auto_now=True, verbose_name='Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
