# Generated by Django 5.2.6 on 2025-09-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-f_actualizacion"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
